name: 🎉 Build Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Set up libpcap-dev
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libpcap-dev -y

#      - name: Get version
#        id: get_version
#        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          go build -o ./ksubdomain-${{ runner.os }} ./cmd/
          chmod +x ksubdomain-${{ runner.os }}
#          tar -cvf ksubdomain-${{ steps.get_version.outputs.VERSION }}-${{ runner.os }}.tar ksubdomain

#      - name: Upload a build artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: ksubdomain-${{ runner.os }}
#          path: ksubdomain
#          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          files: ksubdomain-${{ runner.os }}
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
        env:
          GITHUB_REPOSITORY: boy-hack/ksubdomain